### ISSUE TITLE
3 core links on main page are not working

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/haskell.fpcomplete.com#13]
On https://haskell.fpcomplete.com/ currently, I see the following bubble/button links towards the bottom as not working:
* Learn Haskell
* Applied Haskell
* Start Succeeding

I'm not sure why, but it looks like there is no URL:

```
<p><a class="btn btn-primary">Applied Haskell</a></p>
```

```
<p><a class="btn btn-primary">Start Succeeding</a></p>
```

```
<p><a class="btn btn-primary">Learn Haskell</a></p>
```

**Comment by ketzacoatl** [comment]
It looks like this was introduced in @chrisdone's last commit, so I'll check-in with him on the details here.

**Comment by chrisdone** [comment]
Ah, sorry. Should've noticed that.

**Comment by chrisdone** [comment]
I pushed the links for the buttons. :+1:

**Comment by snoyberg** [comment]
CI finally pushed the change
