### ISSUE TITLE
Clean up tutorial and library content

### ISSUE THREAD

**Issue by snoyberg** [fpco/haskell.fpcomplete.com#7]
There's quite a bit to be done. This issue will track things I find.

* [ ] Review all content and write down more work items
* [x] Add a tutorial for `unliftio`, explaining the `MonadUnliftIO` class, the design of unlifting other libraries, and referencing other tutorials
* [ ] Update other tutorials to use `unliftio` variants, especially `safe-exceptions`
* [x] Consolidate all of the exception handling content into 1, at most 2, tutorials
* [x] Flesh out the `rio` tutorial, referencing `unliftio`, explaining how to use `rio`, etc

**Comment by FranklinChen** [comment]
As part of the cleanup needed: I noticed `synonyms.md` says "Semigroup is not (yet) a superclass of Monoid". This is the case now since base-4.11.0.0.

**Comment by snoyberg** [comment]
Thanks, I'll be sure to address it! Feel free to open up a PR to make the change directly if you'd like as well.

**Comment by snoyberg** [comment]
Done at this point
